# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text2image.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text2image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10text2image.proto\x12\ntext2image\"#\n\x11Text2ImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"2\n\x12Text2ImageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t2c\n\x11Text2ImageService\x12N\n\rGenerateImage\x12\x1d.text2image.Text2ImageRequest\x1a\x1e.text2image.Text2ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text2image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXT2IMAGEREQUEST']._serialized_start=32
  _globals['_TEXT2IMAGEREQUEST']._serialized_end=67
  _globals['_TEXT2IMAGERESPONSE']._serialized_start=69
  _globals['_TEXT2IMAGERESPONSE']._serialized_end=119
  _globals['_TEXT2IMAGESERVICE']._serialized_start=121
  _globals['_TEXT2IMAGESERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
